apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: {{ .Values.repticaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag}}"
          ports:
            - containerPort: {{ .Values.containerPorts.http}}
